# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libp2p/discovery/rendezvous/pb/rendezvous.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/libp2p/discovery/rendezvous/pb/rendezvous.proto\x12\rrendezvous.pb\"\xac\x08\n\x07Message\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".rendezvous.pb.Message.MessageType\x12\x31\n\x08register\x18\x02 \x01(\x0b\x32\x1f.rendezvous.pb.Message.Register\x12\x41\n\x10registerResponse\x18\x03 \x01(\x0b\x32\'.rendezvous.pb.Message.RegisterResponse\x12\x35\n\nunregister\x18\x04 \x01(\x0b\x32!.rendezvous.pb.Message.Unregister\x12\x31\n\x08\x64iscover\x18\x05 \x01(\x0b\x32\x1f.rendezvous.pb.Message.Discover\x12\x41\n\x10\x64iscoverResponse\x18\x06 \x01(\x0b\x32\'.rendezvous.pb.Message.DiscoverResponse\x1a=\n\x08Register\x12\n\n\x02ns\x18\x01 \x01(\t\x12\x18\n\x10signedPeerRecord\x18\x02 \x01(\x0c\x12\x0b\n\x03ttl\x18\x03 \x01(\x04\x1aj\n\x10RegisterResponse\x12\x35\n\x06status\x18\x01 \x01(\x0e\x32%.rendezvous.pb.Message.ResponseStatus\x12\x12\n\nstatusText\x18\x02 \x01(\t\x12\x0b\n\x03ttl\x18\x03 \x01(\x04\x1a\x18\n\nUnregister\x12\n\n\x02ns\x18\x01 \x01(\t\x1a\x35\n\x08\x44iscover\x12\n\n\x02ns\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x04\x12\x0e\n\x06\x63ookie\x18\x03 \x01(\x0c\x1a\xa5\x01\n\x10\x44iscoverResponse\x12\x36\n\rregistrations\x18\x01 \x03(\x0b\x32\x1f.rendezvous.pb.Message.Register\x12\x0e\n\x06\x63ookie\x18\x02 \x01(\x0c\x12\x35\n\x06status\x18\x03 \x01(\x0e\x32%.rendezvous.pb.Message.ResponseStatus\x12\x12\n\nstatusText\x18\x04 \x01(\t\"g\n\x0bMessageType\x12\x0c\n\x08REGISTER\x10\x00\x12\x15\n\x11REGISTER_RESPONSE\x10\x01\x12\x0e\n\nUNREGISTER\x10\x02\x12\x0c\n\x08\x44ISCOVER\x10\x03\x12\x15\n\x11\x44ISCOVER_RESPONSE\x10\x04\"\xbe\x01\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13\x45_INVALID_NAMESPACE\x10\x64\x12 \n\x1c\x45_INVALID_SIGNED_PEER_RECORD\x10\x65\x12\x11\n\rE_INVALID_TTL\x10\x66\x12\x14\n\x10\x45_INVALID_COOKIE\x10g\x12\x15\n\x10\x45_NOT_AUTHORIZED\x10\xc8\x01\x12\x15\n\x10\x45_INTERNAL_ERROR\x10\xac\x02\x12\x12\n\rE_UNAVAILABLE\x10\x90\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libp2p.discovery.rendezvous.pb.rendezvous_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=67
  _globals['_MESSAGE']._serialized_end=1135
  _globals['_MESSAGE_REGISTER']._serialized_start=419
  _globals['_MESSAGE_REGISTER']._serialized_end=480
  _globals['_MESSAGE_REGISTERRESPONSE']._serialized_start=482
  _globals['_MESSAGE_REGISTERRESPONSE']._serialized_end=588
  _globals['_MESSAGE_UNREGISTER']._serialized_start=590
  _globals['_MESSAGE_UNREGISTER']._serialized_end=614
  _globals['_MESSAGE_DISCOVER']._serialized_start=616
  _globals['_MESSAGE_DISCOVER']._serialized_end=669
  _globals['_MESSAGE_DISCOVERRESPONSE']._serialized_start=672
  _globals['_MESSAGE_DISCOVERRESPONSE']._serialized_end=837
  _globals['_MESSAGE_MESSAGETYPE']._serialized_start=839
  _globals['_MESSAGE_MESSAGETYPE']._serialized_end=942
  _globals['_MESSAGE_RESPONSESTATUS']._serialized_start=945
  _globals['_MESSAGE_RESPONSESTATUS']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
