# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webrtc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwebrtc.proto\x12\twebrtc.pb\"\x83\x01\n\x07Message\x12%\n\x04\x66lag\x18\x01 \x01(\x0e\x32\x17.webrtc.pb.Message.Flag\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"@\n\x04\x46lag\x12\x07\n\x03\x46IN\x10\x00\x12\x10\n\x0cSTOP_SENDING\x10\x01\x12\x10\n\x0cRESET_STREAM\x10\x02\x12\x0b\n\x07\x46IN_ACK\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webrtc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=28
  _globals['_MESSAGE']._serialized_end=159
  _globals['_MESSAGE_FLAG']._serialized_start=95
  _globals['_MESSAGE_FLAG']._serialized_end=159
# @@protoc_insertion_point(module_scope)
