# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import autonat_pb2 as autonat__pb2


class AutoNATStub(object):
    """AutoNAT service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dial = channel.unary_unary(
                '/autonat.pb.AutoNAT/Dial',
                request_serializer=autonat__pb2.Message.SerializeToString,
                response_deserializer=autonat__pb2.Message.FromString,
                )


class AutoNATServicer(object):
    """AutoNAT service definition
    """

    def Dial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoNATServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dial': grpc.unary_unary_rpc_method_handler(
                    servicer.Dial,
                    request_deserializer=autonat__pb2.Message.FromString,
                    response_serializer=autonat__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autonat.pb.AutoNAT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoNAT(object):
    """AutoNAT service definition
    """

    @staticmethod
    def Dial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autonat.pb.AutoNAT/Dial',
            autonat__pb2.Message.SerializeToString,
            autonat__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
