# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autonat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rautonat.proto\x12\nautonat.pb\"\xf0\x03\n\x07Message\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.autonat.pb.Message.MessageType\x12&\n\x04\x64ial\x18\x02 \x01(\x0b\x32\x18.autonat.pb.Message.Dial\x12\x36\n\x0c\x64ialResponse\x18\x03 \x01(\x0b\x32 .autonat.pb.Message.DialResponse\x1a%\n\x08PeerInfo\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\x1a\x32\n\x04\x44ial\x12*\n\x04peer\x18\x01 \x01(\x0b\x32\x1c.autonat.pb.Message.PeerInfo\x1a\x64\n\x0c\x44ialResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".autonat.pb.Message.ResponseStatus\x12\x12\n\nstatusText\x18\x02 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\x0c\"*\n\x0bMessageType\x12\x08\n\x04\x44IAL\x10\x00\x12\x11\n\rDIAL_RESPONSE\x10\x01\"i\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0c\x45_DIAL_ERROR\x10\x64\x12\x12\n\x0e\x45_DIAL_REFUSED\x10\x65\x12\x12\n\rE_BAD_REQUEST\x10\xc8\x01\x12\x15\n\x10\x45_INTERNAL_ERROR\x10\xac\x02\x32=\n\x07\x41utoNAT\x12\x32\n\x04\x44ial\x12\x13.autonat.pb.Message\x1a\x13.autonat.pb.Message\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=30
  _globals['_MESSAGE']._serialized_end=526
  _globals['_MESSAGE_PEERINFO']._serialized_start=184
  _globals['_MESSAGE_PEERINFO']._serialized_end=221
  _globals['_MESSAGE_DIAL']._serialized_start=223
  _globals['_MESSAGE_DIAL']._serialized_end=273
  _globals['_MESSAGE_DIALRESPONSE']._serialized_start=275
  _globals['_MESSAGE_DIALRESPONSE']._serialized_end=375
  _globals['_MESSAGE_MESSAGETYPE']._serialized_start=377
  _globals['_MESSAGE_MESSAGETYPE']._serialized_end=419
  _globals['_MESSAGE_RESPONSESTATUS']._serialized_start=421
  _globals['_MESSAGE_RESPONSESTATUS']._serialized_end=526
  _globals['_AUTONAT']._serialized_start=528
  _globals['_AUTONAT']._serialized_end=589
# @@protoc_insertion_point(module_scope)
